node {
  stage('do something with git') {  
    sshagent (credentials: ['github']) {
      // get the last commit id from a repository you own
      sh 'git ls-remote -h --refs git@github.com:richard3000/private-git-repo.git master |awk "{print $1}"'
    }
  }
}
